controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    position_controller:  # 控制器名字, 可以随便起
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:  # 关节状态发布器的名字, 可以随便起
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:  # 控制器名字, 要和上面的一致
  ros__parameters:
    joints:
      - joint1
    command_interfaces:  # 命令接口, 可以是位置, 速度, 加速度
      - position
    state_interfaces:  # 状态反馈接口, 可以是位置, 速度, 加速度
      - position

joint_state_broadcaster:  # 关节状态发布器的名字, 要和上面的一致
  ros__parameters:
    use_urdf_to_filter: true